### PR TITLE
Update ban.js

### PR DESCRIPTION
**Pull request by NekWasTaken**
Test this shit before you merge it.

### CODE REVIEW

**Comment by Craftzman7** [comment]
Don't worry I will

**Review by Craftzman7 — CHANGES_REQUESTED** [review]
Um this checks for kick members and this is the ban command

**Comment by NekWasTaken** [comment]
Oh fuck, I just copied and pasted from the last PR and forgot to change it,

**Comment by Craftzman7** [comment]
As this is copied and pasted please reference #20

**Pull request merged**
